<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20181113130842 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE galleries CHANGE id_type id_type INT DEFAULT NULL');
        $this->addSql('ALTER TABLE applications CHANGE id_label id_label INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE categories CHANGE id_type id_type INT DEFAULT NULL, CHANGE id_order id_order INT DEFAULT NULL, CHANGE id_label id_label INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE categories_sub_categories DROP FOREIGN KEY categories_sub_categories_ibfk_1');
        $this->addSql('ALTER TABLE categories_sub_categories DROP FOREIGN KEY categories_sub_categories_ibfk_2');
        $this->addSql('ALTER TABLE categories_sub_categories ADD CONSTRAINT FK_A7C756315697F554 FOREIGN KEY (id_category) REFERENCES categories (id_category)');
        $this->addSql('ALTER TABLE categories_sub_categories ADD CONSTRAINT FK_A7C7563115CE69BF FOREIGN KEY (id_subcategory) REFERENCES subcategories (id_subcategory)');
        $this->addSql('ALTER TABLE categories_sub_categories RENAME INDEX id_subcategory TO IDX_A7C7563115CE69BF');
        $this->addSql('ALTER TABLE content CHANGE id_subcategory id_subcategory INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE cv CHANGE id_order id_order INT DEFAULT NULL, CHANGE id_working_license id_working_license INT DEFAULT NULL, CHANGE id_department id_department INT DEFAULT NULL, CHANGE id_type_cv id_type_cv INT DEFAULT NULL, CHANGE id_country id_country INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE cv_driver_s_license DROP FOREIGN KEY cv_driver_s_license_ibfk_1');
        $this->addSql('ALTER TABLE cv_driver_s_license DROP FOREIGN KEY cv_driver_s_license_ibfk_2');
        $this->addSql('ALTER TABLE cv_driver_s_license ADD CONSTRAINT FK_F3EF539476120795 FOREIGN KEY (id_cv) REFERENCES cv (id_cv)');
        $this->addSql('ALTER TABLE cv_driver_s_license ADD CONSTRAINT FK_F3EF5394A58D7F7B FOREIGN KEY (id_driver_s_license) REFERENCES driver_s_license (id_driver_s_license)');
        $this->addSql('ALTER TABLE cv_driver_s_license RENAME INDEX id_driver_s_license TO IDX_F3EF5394A58D7F7B');
        $this->addSql('ALTER TABLE cv_experiences DROP FOREIGN KEY cv_experiences_ibfk_1');
        $this->addSql('ALTER TABLE cv_experiences DROP FOREIGN KEY cv_experiences_ibfk_2');
        $this->addSql('ALTER TABLE cv_experiences ADD CONSTRAINT FK_9C7C0A8D76120795 FOREIGN KEY (id_cv) REFERENCES cv (id_cv)');
        $this->addSql('ALTER TABLE cv_experiences ADD CONSTRAINT FK_9C7C0A8DA01A41D4 FOREIGN KEY (id_experience) REFERENCES experiences (id_experience)');
        $this->addSql('ALTER TABLE cv_experiences RENAME INDEX id_experience TO IDX_9C7C0A8DA01A41D4');
        $this->addSql('ALTER TABLE cv_hobbies DROP FOREIGN KEY cv_hobbies_ibfk_1');
        $this->addSql('ALTER TABLE cv_hobbies DROP FOREIGN KEY cv_hobbies_ibfk_2');
        $this->addSql('ALTER TABLE cv_hobbies ADD CONSTRAINT FK_7343675376120795 FOREIGN KEY (id_cv) REFERENCES cv (id_cv)');
        $this->addSql('ALTER TABLE cv_hobbies ADD CONSTRAINT FK_734367533BAB1C1A FOREIGN KEY (id_hobbie) REFERENCES hobbies (id_hobbie)');
        $this->addSql('ALTER TABLE cv_hobbies RENAME INDEX id_hobbie TO IDX_734367533BAB1C1A');
        $this->addSql('ALTER TABLE cv_skills DROP FOREIGN KEY cv_skills_ibfk_1');
        $this->addSql('ALTER TABLE cv_skills DROP FOREIGN KEY cv_skills_ibfk_2');
        $this->addSql('ALTER TABLE cv_skills ADD CONSTRAINT FK_58B61F5576120795 FOREIGN KEY (id_cv) REFERENCES cv (id_cv)');
        $this->addSql('ALTER TABLE cv_skills ADD CONSTRAINT FK_58B61F55B0B8A547 FOREIGN KEY (id_skill) REFERENCES skills (id_skill)');
        $this->addSql('ALTER TABLE cv_skills RENAME INDEX id_skill TO IDX_58B61F55B0B8A547');
        $this->addSql('ALTER TABLE cv_training DROP FOREIGN KEY cv_training_ibfk_1');
        $this->addSql('ALTER TABLE cv_training DROP FOREIGN KEY cv_training_ibfk_2');
        $this->addSql('ALTER TABLE cv_training ADD CONSTRAINT FK_443D6F4B76120795 FOREIGN KEY (id_cv) REFERENCES cv (id_cv)');
        $this->addSql('ALTER TABLE cv_training ADD CONSTRAINT FK_443D6F4B85C9661A FOREIGN KEY (id_training) REFERENCES training (id_training)');
        $this->addSql('ALTER TABLE cv_training RENAME INDEX id_training TO IDX_443D6F4B85C9661A');
        $this->addSql('ALTER TABLE departments CHANGE id_country id_country INT DEFAULT NULL');
        $this->addSql('ALTER TABLE experiences CHANGE id_order id_order INT DEFAULT NULL, CHANGE id_label id_label INT DEFAULT NULL, CHANGE id_business_name id_business_name INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE footer CHANGE id_menu id_menu INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE header CHANGE id_menu id_menu INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE hobbies CHANGE id_order id_order INT DEFAULT NULL, CHANGE id_label id_label INT DEFAULT NULL');
        $this->addSql('ALTER TABLE labels CHANGE id_type_label id_type_label INT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_content CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_content_menus DROP FOREIGN KEY menu_content_menus_ibfk_1');
        $this->addSql('ALTER TABLE menu_content_menus DROP FOREIGN KEY menu_content_menus_ibfk_2');
        $this->addSql('ALTER TABLE menu_content_menus ADD CONSTRAINT FK_3F75098B55DF5865 FOREIGN KEY (id_menu_content) REFERENCES menu_content (id_menu_content)');
        $this->addSql('ALTER TABLE menu_content_menus ADD CONSTRAINT FK_3F75098BF6252691 FOREIGN KEY (id_menu) REFERENCES menus (id_menu)');
        $this->addSql('ALTER TABLE menu_content_menus RENAME INDEX id_menu TO IDX_3F75098BF6252691');
        $this->addSql('ALTER TABLE menus CHANGE id_type id_type INT DEFAULT NULL, CHANGE id_order id_order INT DEFAULT NULL, CHANGE id_label id_label INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE menus_categories DROP FOREIGN KEY menus_categories_ibfk_1');
        $this->addSql('ALTER TABLE menus_categories DROP FOREIGN KEY menus_categories_ibfk_2');
        $this->addSql('ALTER TABLE menus_categories ADD CONSTRAINT FK_2C7F3E25F6252691 FOREIGN KEY (id_menu) REFERENCES menus (id_menu)');
        $this->addSql('ALTER TABLE menus_categories ADD CONSTRAINT FK_2C7F3E255697F554 FOREIGN KEY (id_category) REFERENCES categories (id_category)');
        $this->addSql('ALTER TABLE menus_categories RENAME INDEX id_category TO IDX_2C7F3E255697F554');
        $this->addSql('ALTER TABLE navbar CHANGE id_menu id_menu INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE orders CHANGE id_order_type id_order_type INT DEFAULT NULL');
        $this->addSql('ALTER TABLE portfolios CHANGE id_header id_header INT DEFAULT NULL, CHANGE id_navbar id_navbar INT DEFAULT NULL, CHANGE id_menu_content id_menu_content INT DEFAULT NULL, CHANGE id_widget id_widget INT DEFAULT NULL, CHANGE id_content id_content INT DEFAULT NULL, CHANGE id_footer id_footer INT DEFAULT NULL, CHANGE id id INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE portfolios_applications DROP FOREIGN KEY portfolios_applications_ibfk_1');
        $this->addSql('ALTER TABLE portfolios_applications DROP FOREIGN KEY portfolios_applications_ibfk_2');
        $this->addSql('ALTER TABLE portfolios_applications ADD CONSTRAINT FK_60EDC61729D8AC45 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio)');
        $this->addSql('ALTER TABLE portfolios_applications ADD CONSTRAINT FK_60EDC61757CA9895 FOREIGN KEY (id_app) REFERENCES applications (id_app)');
        $this->addSql('ALTER TABLE portfolios_applications RENAME INDEX id_app TO IDX_60EDC61757CA9895');
        $this->addSql('ALTER TABLE portfolios_cv DROP FOREIGN KEY portfolios_cv_ibfk_1');
        $this->addSql('ALTER TABLE portfolios_cv DROP FOREIGN KEY portfolios_cv_ibfk_2');
        $this->addSql('ALTER TABLE portfolios_cv ADD CONSTRAINT FK_14B5F9B29D8AC45 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio)');
        $this->addSql('ALTER TABLE portfolios_cv ADD CONSTRAINT FK_14B5F9B76120795 FOREIGN KEY (id_cv) REFERENCES cv (id_cv)');
        $this->addSql('ALTER TABLE portfolios_cv RENAME INDEX id_cv TO IDX_14B5F9B76120795');
        $this->addSql('ALTER TABLE portfolios_galleries DROP FOREIGN KEY portfolios_galleries_ibfk_1');
        $this->addSql('ALTER TABLE portfolios_galleries DROP FOREIGN KEY portfolios_galleries_ibfk_2');
        $this->addSql('ALTER TABLE portfolios_galleries ADD CONSTRAINT FK_43216C829D8AC45 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio)');
        $this->addSql('ALTER TABLE portfolios_galleries ADD CONSTRAINT FK_43216C899B6D14A FOREIGN KEY (id_gallery) REFERENCES galleries (id_gallery)');
        $this->addSql('ALTER TABLE portfolios_galleries RENAME INDEX id_gallery TO IDX_43216C899B6D14A');
        $this->addSql('ALTER TABLE portfolios_projects DROP FOREIGN KEY portfolios_projects_ibfk_1');
        $this->addSql('ALTER TABLE portfolios_projects DROP FOREIGN KEY portfolios_projects_ibfk_2');
        $this->addSql('ALTER TABLE portfolios_projects CHANGE id_portfolio id_portfolio INT NOT NULL');
        $this->addSql('ALTER TABLE portfolios_projects ADD CONSTRAINT FK_D99A84B629D8AC45 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio)');
        $this->addSql('ALTER TABLE portfolios_projects ADD CONSTRAINT FK_D99A84B6F12E799E FOREIGN KEY (id_project) REFERENCES projects (id_project)');
        $this->addSql('ALTER TABLE portfolios_projects RENAME INDEX id_project TO IDX_D99A84B6F12E799E');
        $this->addSql('ALTER TABLE portfolios_websites DROP FOREIGN KEY portfolios_websites_ibfk_1');
        $this->addSql('ALTER TABLE portfolios_websites DROP FOREIGN KEY portfolios_websites_ibfk_2');
        $this->addSql('ALTER TABLE portfolios_websites ADD CONSTRAINT FK_A02EE09F29D8AC45 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio)');
        $this->addSql('ALTER TABLE portfolios_websites ADD CONSTRAINT FK_A02EE09F8B6DD00B FOREIGN KEY (id_web) REFERENCES websites (id_web)');
        $this->addSql('ALTER TABLE portfolios_websites RENAME INDEX id_web TO IDX_A02EE09F8B6DD00B');
        $this->addSql('ALTER TABLE projects CHANGE id_project id_project INT AUTO_INCREMENT NOT NULL, CHANGE id_business_name id_business_name INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL, CHANGE valuenow valuenow INT DEFAULT NULL, CHANGE valuemin valuemin INT DEFAULT NULL');
        $this->addSql('ALTER TABLE scheduler CHANGE id_schedule id_schedule INT AUTO_INCREMENT NOT NULL, CHANGE id_label id_label INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE skills CHANGE id_order id_order INT DEFAULT NULL, CHANGE id_type_skill id_type_skill INT DEFAULT NULL, CHANGE id_label id_label INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE subcategories CHANGE id_type id_type INT DEFAULT NULL, CHANGE id_order id_order INT DEFAULT NULL, CHANGE id_label id_label INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE tasks CHANGE id_task id_task INT AUTO_INCREMENT NOT NULL, CHANGE id_project id_project INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL, CHANGE valuenow valuenow INT DEFAULT NULL, CHANGE valuemin valuemin INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tasks_scheduler DROP FOREIGN KEY tasks_scheduler_ibfk_1');
        $this->addSql('ALTER TABLE tasks_scheduler DROP FOREIGN KEY tasks_scheduler_ibfk_2');
        $this->addSql('ALTER TABLE tasks_scheduler ADD CONSTRAINT FK_9B351BBAD95EC727 FOREIGN KEY (id_task) REFERENCES tasks (id_task)');
        $this->addSql('ALTER TABLE tasks_scheduler ADD CONSTRAINT FK_9B351BBAAE3FD6E FOREIGN KEY (id_schedule) REFERENCES scheduler (id_schedule)');
        $this->addSql('ALTER TABLE tasks_scheduler RENAME INDEX id_schedule TO IDX_9B351BBAAE3FD6E');
        $this->addSql('ALTER TABLE training CHANGE id_order id_order INT DEFAULT NULL, CHANGE id_label id_label INT DEFAULT NULL, CHANGE id_business_name id_business_name INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE type_skills CHANGE id_label id_label INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE active active TINYINT(1) DEFAULT NULL, CHANGE visible visible TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE websites CHANGE id_label id_label INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE widget CHANGE id_category id_category INT DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE applications CHANGE id_label id_label INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE categories CHANGE id_type id_type INT NOT NULL, CHANGE id_order id_order INT NOT NULL, CHANGE id_label id_label INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE categories_sub_categories DROP FOREIGN KEY FK_A7C756315697F554');
        $this->addSql('ALTER TABLE categories_sub_categories DROP FOREIGN KEY FK_A7C7563115CE69BF');
        $this->addSql('ALTER TABLE categories_sub_categories ADD CONSTRAINT categories_sub_categories_ibfk_1 FOREIGN KEY (id_category) REFERENCES categories (id_category) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE categories_sub_categories ADD CONSTRAINT categories_sub_categories_ibfk_2 FOREIGN KEY (id_subcategory) REFERENCES subcategories (id_subcategory) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE categories_sub_categories RENAME INDEX idx_a7c7563115ce69bf TO id_subcategory');
        $this->addSql('ALTER TABLE content CHANGE id_subcategory id_subcategory INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE cv CHANGE id_order id_order INT NOT NULL, CHANGE id_working_license id_working_license INT NOT NULL, CHANGE id_department id_department INT NOT NULL, CHANGE id_type_cv id_type_cv INT NOT NULL, CHANGE id_country id_country INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE cv_driver_s_license DROP FOREIGN KEY FK_F3EF539476120795');
        $this->addSql('ALTER TABLE cv_driver_s_license DROP FOREIGN KEY FK_F3EF5394A58D7F7B');
        $this->addSql('ALTER TABLE cv_driver_s_license ADD CONSTRAINT cv_driver_s_license_ibfk_1 FOREIGN KEY (id_cv) REFERENCES cv (id_cv) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_driver_s_license ADD CONSTRAINT cv_driver_s_license_ibfk_2 FOREIGN KEY (id_driver_s_license) REFERENCES driver_s_license (id_driver_s_license) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_driver_s_license RENAME INDEX idx_f3ef5394a58d7f7b TO id_driver_s_license');
        $this->addSql('ALTER TABLE cv_experiences DROP FOREIGN KEY FK_9C7C0A8D76120795');
        $this->addSql('ALTER TABLE cv_experiences DROP FOREIGN KEY FK_9C7C0A8DA01A41D4');
        $this->addSql('ALTER TABLE cv_experiences ADD CONSTRAINT cv_experiences_ibfk_1 FOREIGN KEY (id_cv) REFERENCES cv (id_cv) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_experiences ADD CONSTRAINT cv_experiences_ibfk_2 FOREIGN KEY (id_experience) REFERENCES experiences (id_experience) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_experiences RENAME INDEX idx_9c7c0a8da01a41d4 TO id_experience');
        $this->addSql('ALTER TABLE cv_hobbies DROP FOREIGN KEY FK_7343675376120795');
        $this->addSql('ALTER TABLE cv_hobbies DROP FOREIGN KEY FK_734367533BAB1C1A');
        $this->addSql('ALTER TABLE cv_hobbies ADD CONSTRAINT cv_hobbies_ibfk_1 FOREIGN KEY (id_cv) REFERENCES cv (id_cv) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_hobbies ADD CONSTRAINT cv_hobbies_ibfk_2 FOREIGN KEY (id_hobbie) REFERENCES hobbies (id_hobbie) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_hobbies RENAME INDEX idx_734367533bab1c1a TO id_hobbie');
        $this->addSql('ALTER TABLE cv_skills DROP FOREIGN KEY FK_58B61F5576120795');
        $this->addSql('ALTER TABLE cv_skills DROP FOREIGN KEY FK_58B61F55B0B8A547');
        $this->addSql('ALTER TABLE cv_skills ADD CONSTRAINT cv_skills_ibfk_1 FOREIGN KEY (id_cv) REFERENCES cv (id_cv) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_skills ADD CONSTRAINT cv_skills_ibfk_2 FOREIGN KEY (id_skill) REFERENCES skills (id_skill) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_skills RENAME INDEX idx_58b61f55b0b8a547 TO id_skill');
        $this->addSql('ALTER TABLE cv_training DROP FOREIGN KEY FK_443D6F4B76120795');
        $this->addSql('ALTER TABLE cv_training DROP FOREIGN KEY FK_443D6F4B85C9661A');
        $this->addSql('ALTER TABLE cv_training ADD CONSTRAINT cv_training_ibfk_1 FOREIGN KEY (id_cv) REFERENCES cv (id_cv) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_training ADD CONSTRAINT cv_training_ibfk_2 FOREIGN KEY (id_training) REFERENCES training (id_training) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cv_training RENAME INDEX idx_443d6f4b85c9661a TO id_training');
        $this->addSql('ALTER TABLE departments CHANGE id_country id_country INT NOT NULL');
        $this->addSql('ALTER TABLE experiences CHANGE id_order id_order INT NOT NULL, CHANGE id_label id_label INT NOT NULL, CHANGE id_business_name id_business_name INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE footer CHANGE id_menu id_menu INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE galleries CHANGE id_type id_type INT NOT NULL');
        $this->addSql('ALTER TABLE header CHANGE id_menu id_menu INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE hobbies CHANGE id_order id_order INT NOT NULL, CHANGE id_label id_label INT NOT NULL');
        $this->addSql('ALTER TABLE labels CHANGE id_type_label id_type_label INT NOT NULL');
        $this->addSql('ALTER TABLE menu_content CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE menu_content_menus DROP FOREIGN KEY FK_3F75098B55DF5865');
        $this->addSql('ALTER TABLE menu_content_menus DROP FOREIGN KEY FK_3F75098BF6252691');
        $this->addSql('ALTER TABLE menu_content_menus ADD CONSTRAINT menu_content_menus_ibfk_1 FOREIGN KEY (id_menu_content) REFERENCES menu_content (id_menu_content) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_content_menus ADD CONSTRAINT menu_content_menus_ibfk_2 FOREIGN KEY (id_menu) REFERENCES menus (id_menu) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_content_menus RENAME INDEX idx_3f75098bf6252691 TO id_menu');
        $this->addSql('ALTER TABLE menus CHANGE id_type id_type INT NOT NULL, CHANGE id_order id_order INT NOT NULL, CHANGE id_label id_label INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE menus_categories DROP FOREIGN KEY FK_2C7F3E25F6252691');
        $this->addSql('ALTER TABLE menus_categories DROP FOREIGN KEY FK_2C7F3E255697F554');
        $this->addSql('ALTER TABLE menus_categories ADD CONSTRAINT menus_categories_ibfk_1 FOREIGN KEY (id_menu) REFERENCES menus (id_menu) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menus_categories ADD CONSTRAINT menus_categories_ibfk_2 FOREIGN KEY (id_category) REFERENCES categories (id_category) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menus_categories RENAME INDEX idx_2c7f3e255697f554 TO id_category');
        $this->addSql('ALTER TABLE navbar CHANGE id_menu id_menu INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE orders CHANGE id_order_type id_order_type INT NOT NULL');
        $this->addSql('ALTER TABLE portfolios CHANGE id_header id_header INT NOT NULL, CHANGE id_navbar id_navbar INT NOT NULL, CHANGE id_menu_content id_menu_content INT NOT NULL, CHANGE id_widget id_widget INT NOT NULL, CHANGE id_content id_content INT NOT NULL, CHANGE id_footer id_footer INT NOT NULL, CHANGE id id INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE portfolios_applications DROP FOREIGN KEY FK_60EDC61729D8AC45');
        $this->addSql('ALTER TABLE portfolios_applications DROP FOREIGN KEY FK_60EDC61757CA9895');
        $this->addSql('ALTER TABLE portfolios_applications ADD CONSTRAINT portfolios_applications_ibfk_1 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_applications ADD CONSTRAINT portfolios_applications_ibfk_2 FOREIGN KEY (id_app) REFERENCES applications (id_app) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_applications RENAME INDEX idx_60edc61757ca9895 TO id_app');
        $this->addSql('ALTER TABLE portfolios_cv DROP FOREIGN KEY FK_14B5F9B29D8AC45');
        $this->addSql('ALTER TABLE portfolios_cv DROP FOREIGN KEY FK_14B5F9B76120795');
        $this->addSql('ALTER TABLE portfolios_cv ADD CONSTRAINT portfolios_cv_ibfk_1 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_cv ADD CONSTRAINT portfolios_cv_ibfk_2 FOREIGN KEY (id_cv) REFERENCES cv (id_cv) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_cv RENAME INDEX idx_14b5f9b76120795 TO id_cv');
        $this->addSql('ALTER TABLE portfolios_galleries DROP FOREIGN KEY FK_43216C829D8AC45');
        $this->addSql('ALTER TABLE portfolios_galleries DROP FOREIGN KEY FK_43216C899B6D14A');
        $this->addSql('ALTER TABLE portfolios_galleries ADD CONSTRAINT portfolios_galleries_ibfk_1 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_galleries ADD CONSTRAINT portfolios_galleries_ibfk_2 FOREIGN KEY (id_gallery) REFERENCES galleries (id_gallery) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_galleries RENAME INDEX idx_43216c899b6d14a TO id_gallery');
        $this->addSql('ALTER TABLE portfolios_projects DROP FOREIGN KEY FK_D99A84B629D8AC45');
        $this->addSql('ALTER TABLE portfolios_projects DROP FOREIGN KEY FK_D99A84B6F12E799E');
        $this->addSql('ALTER TABLE portfolios_projects CHANGE id_portfolio id_portfolio INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE portfolios_projects ADD CONSTRAINT portfolios_projects_ibfk_1 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_projects ADD CONSTRAINT portfolios_projects_ibfk_2 FOREIGN KEY (id_project) REFERENCES projects (id_project) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_projects RENAME INDEX idx_d99a84b6f12e799e TO id_project');
        $this->addSql('ALTER TABLE portfolios_websites DROP FOREIGN KEY FK_A02EE09F29D8AC45');
        $this->addSql('ALTER TABLE portfolios_websites DROP FOREIGN KEY FK_A02EE09F8B6DD00B');
        $this->addSql('ALTER TABLE portfolios_websites ADD CONSTRAINT portfolios_websites_ibfk_1 FOREIGN KEY (id_portfolio) REFERENCES portfolios (id_portfolio) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_websites ADD CONSTRAINT portfolios_websites_ibfk_2 FOREIGN KEY (id_web) REFERENCES websites (id_web) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolios_websites RENAME INDEX idx_a02ee09f8b6dd00b TO id_web');
        $this->addSql('ALTER TABLE projects CHANGE id_project id_project INT NOT NULL, CHANGE id_business_name id_business_name INT DEFAULT 0, CHANGE active active TINYINT(1) DEFAULT \'0\', CHANGE valuenow valuenow INT DEFAULT 0, CHANGE valuemin valuemin INT DEFAULT 0');
        $this->addSql('ALTER TABLE scheduler CHANGE id_schedule id_schedule INT NOT NULL, CHANGE id_label id_label INT DEFAULT 0, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE skills CHANGE id_order id_order INT NOT NULL, CHANGE id_type_skill id_type_skill INT NOT NULL, CHANGE id_label id_label INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE subcategories CHANGE id_type id_type INT NOT NULL, CHANGE id_order id_order INT NOT NULL, CHANGE id_label id_label INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE tasks CHANGE id_task id_task INT NOT NULL, CHANGE id_project id_project INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\', CHANGE valuenow valuenow INT DEFAULT 0, CHANGE valuemin valuemin INT DEFAULT 0');
        $this->addSql('ALTER TABLE tasks_scheduler DROP FOREIGN KEY FK_9B351BBAD95EC727');
        $this->addSql('ALTER TABLE tasks_scheduler DROP FOREIGN KEY FK_9B351BBAAE3FD6E');
        $this->addSql('ALTER TABLE tasks_scheduler ADD CONSTRAINT tasks_scheduler_ibfk_1 FOREIGN KEY (id_task) REFERENCES tasks (id_task) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tasks_scheduler ADD CONSTRAINT tasks_scheduler_ibfk_2 FOREIGN KEY (id_schedule) REFERENCES scheduler (id_schedule) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tasks_scheduler RENAME INDEX idx_9b351bbaae3fd6e TO id_schedule');
        $this->addSql('ALTER TABLE training CHANGE id_order id_order INT NOT NULL, CHANGE id_label id_label INT NOT NULL, CHANGE id_business_name id_business_name INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE type_skills CHANGE id_label id_label INT NOT NULL');
        $this->addSql('ALTER TABLE user CHANGE active active TINYINT(1) DEFAULT \'0\', CHANGE visible visible TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE websites CHANGE id_label id_label INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE widget CHANGE id_category id_category INT NOT NULL, CHANGE active active TINYINT(1) DEFAULT \'0\'');
    }
}
